# my global config
global:
  scrape_interval:     5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
    - targets: ['localhost:9090']
      labels:
        group: 'prometheus'
  - job_name: 'cadvisor'
    static_configs:
    - targets: ['3.16.212.239:8080']
      labels:
        group: 'flask'
    - targets: ['52.14.53.139:8080']
      labels:
        group: 'grafana'
    - targets: ['3.138.141.1:8080']
      labels:
        group: 'jupyter'